version: '3.8'

networks:
  aw-network:
    driver: bridge

services:
  sqs-local:
    image: "localstack/localstack"
    container_name: localstack-local
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'
    volumes:
      - "./src/main/resources/localstack/create-queue.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis-local:
    image: redis:7.0.11-alpine3.18
    container_name: redis-local
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - "9090:9090"

#  grafana:
#    image: grafana/grafana:latest
#    volumes:
#      - grafana_data:/grafana
#    networks:
#      - aw-network
#    ports:
#      - "3000:3000"

#volumes:
#  redis_data:
##  prometheus_data:
##  grafana_data: