
tpm:
  interval-seconds: 60

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: batata
      secret-key: batata
    uri: http://localhost:4566
    queue:
      name: sqs-cadastro-cliente
    s3:
      uri: https://s3.localhost.localstack.cloud:4566
      bucket-name: "bucket-cadastro-cliente-config-rate-limit"
      rate-limit-config-key: "rateLimitConfig.json"

redis:
  host: localhost
  port: 6379


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true