
tpm:
  interval-seconds: 60
  token-size: 300

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: batata
      secret-key: batata
    queue:
      uri: http://localhost:4566
      name: sqs-cadastro-cliente

redis:
  host: localhost
  port: 6379


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true